### ISSUE TITLE
.htaccess removal of [P] flag

### ISSUE THREAD

**Issue by xvxd4sh** [karendm/ansible-role-megazord-composition#8]
# 💡 Summary #

Proxy server is not configured however cs2modrewrite configure the .htaccess file with a proxy flag so, we remove it. 

## Motivation and context ##

we need the removal of the proxy flag for the smooth function of the http redirector

This would be useful because we would not need to configure additional functionality that serves minimal purpose

## Acceptance criteria ##

removal using string manipulation

- [x] Python

**Comment by bhambleton** [comment]
This is no longer necessary because mod_proxy is now being used by Apache.
